export interface ResearchReport {
  summary: string
  findings: string[]
  opportunities: string[]
  nextActions: string[]
}

export type ReviewAction = 'clarify' | 'challenge' | 'refine'

export function createReviewReport(action: ReviewAction, instruction: string, previous: ResearchReport): ResearchReport {
  const direction = instruction.trim() || 'Make the result more useful and specific.'
  if (action === 'clarify') return { summary: `Clarification requested: “${direction}” The recommendation rests on observable usefulness, explicit economic receipts, and repeat operator behavior—not novelty alone.`, findings: [`The original conclusion follows from this premise: ${previous.findings[0]}`, 'The strongest assumption is that users value an operator more when its output, cost, and progression remain attributable to one NFT.', 'Confidence should fall if repeated missions do not improve retention or if users ignore skill and receipt history.'], opportunities: ['Verify the key assumption with returning-user behavior.', 'Attach a primary source or product metric to every consequential claim.', 'Record which explanation resolved the reviewer’s uncertainty.'], nextActions: ['Confirm whether this explanation answers the review request.', 'Mark any remaining unsupported assumption.', 'Accept the current version or request a scoped revision.'] }
  if (action === 'challenge') return { summary: `Challenge applied: “${direction}” The strongest counter-position is that operator identity and RF receipts add ceremony without enough utility; the proposal survives only where repeated work becomes measurably better or more accountable.`, findings: ['A generic AI tool may complete the same task with less friction.', 'Token spending is defensible only when the skill, history, or ownership context creates additional value.', `The original case remains strongest here: ${previous.opportunities[0]}`], opportunities: ['Measure whether users reopen the same operator for related work.', 'Compare mission completion against a generic assistant baseline.', 'Expose failure rate and revision count alongside successful receipts.'], nextActions: ['Define one falsifiable success metric.', 'Run the smallest comparison test.', 'Keep only the claims that remain supported after the challenge.'] }
  return { summary: `Version revised from the instruction: “${direction}” The deliverable now leads with the practical outcome, makes its assumptions explicit, and ends with an executable next step.`, findings: previous.findings.map((finding, index) => index === 0 ? `${finding} This is now the primary evidence for the revised direction.` : finding), opportunities: previous.opportunities.map((opportunity, index) => index === 0 ? `${opportunity} Prioritize this before expanding scope.` : opportunity), nextActions: [`Apply the requested direction: ${direction}`, previous.nextActions[0], 'Review this version against the original brief and accept it only if the outcome is materially stronger.'] }
}

export function createDemoReport(topic: string, missionId = 'research'): ResearchReport {
  const subject = topic.trim() || 'Rare Friends ecosystem opportunities for developers'

  if (missionId === 'content') return { summary: `I turned “${subject}” into a social campaign designed for clarity, conversation, and measurable action—not an analytics report.`, findings: ['Hook: lead with the outcome in the first eight words so the value survives feed truncation.', 'Audience tension: builders want proof of utility; collectors want identity and belonging.', 'Recommended format: one launch post, a five-part thread, and two reply prompts for community participation.'], opportunities: ['Test a utility-led hook against a character-led hook.', 'Use the operator’s actual mission receipt as social proof.', 'Invite replies with one specific question instead of a generic call to engage.'], nextActions: ['Publish the short launch post during the audience’s strongest activity window.', 'Reply with the feature thread within fifteen minutes.', 'Review saves, qualified replies, and click-through after 24 hours.'] }
  if (missionId === 'strategy') return { summary: `I pressure-tested “${subject}” as a market narrative. The strongest position connects an observable user problem to a repeatable operator behavior.`, findings: ['The narrative becomes weak when it promises general AI capability without verifiable receipts.', 'Differentiation improves when each NFT owns skills, memory, and an operating wallet.', 'The primary risk is presenting simulated demand as proven demand; label experiments and measure conversion.'], opportunities: ['Position skills as productive NFT upgrades rather than static traits.', 'Use developer revenue share to attract specialized capabilities.', 'Publish operator success rates so marketplace prices emerge from evidence.'], nextActions: ['Define the one audience segment and desired behavior for the next campaign.', 'Run a seven-day message test across three narrative angles.', 'Promote only the angle that produces qualified mission starts.'] }
  if (missionId === 'quick-ask') return { summary: `Direct answer: ${subject} should be evaluated by usefulness, evidence quality, and repeat usage—not novelty alone.`, findings: ['Start with the decision the user needs to make.', 'Separate observed facts from operator inference.', 'Attach a next action that can be completed today.'], opportunities: ['Convert this answer into a full analytics mission.', 'Save the conclusion to the operator’s working memory.', 'Compare it against a second specialist skill.'], nextActions: ['Confirm the desired outcome.', 'Gather one primary source.', 'Run the smallest useful test.'] }
  if (missionId === 'advanced') return { summary: `I converted “${subject}” into a controlled operating plan with clear decision gates, dependencies, and evidence requirements.`, findings: ['The mission should begin with a measurable completion condition so later work cannot drift from the intended outcome.', 'External data, wallet actions, and publishing permissions are separate dependencies and should be authorized only when required.', 'Every autonomous step needs a receipt containing its input, output, cost, and confidence so the operator remains auditable.'], opportunities: ['Run independent research and message-drafting steps in parallel once the evidence scope is approved.', 'Use installed specialist skills only for the stages where they improve accuracy or execution.', 'Turn a successful run into a reusable mission template with a known RF budget.'], nextActions: ['Approve the outcome, maximum RF budget, and actions the operator may take.', 'Complete the evidence-gathering stage and pause at the first decision gate.', 'Review the final receipt before authorizing any external action.'] }
  if (missionId === 'deep') return { summary: `I framed “${subject}” as a staged investigation: test the strongest competing explanations, close the highest-impact evidence gaps, then recommend an action with an explicit confidence level.`, findings: ['The first plausible explanation should not be treated as the conclusion; at least one credible alternative must be tested.', 'Current external facts require primary-source verification, including the observation date and scope.', 'A useful conclusion states both what the evidence supports and what would cause the recommendation to change.'], opportunities: ['Build an evidence table that separates verified facts, assumptions, and unresolved questions.', 'Compare results across multiple time windows or cohorts to avoid a misleading snapshot.', 'Preserve the investigation as operator memory so future missions can update rather than repeat it.'], nextActions: ['Define the decision this investigation must support and its acceptable confidence threshold.', 'Collect the smallest set of primary evidence capable of disproving each hypothesis.', 'Synthesize the evidence, document uncertainty, and schedule the next verification point.'] }

  return {
    summary: `${subject} is best approached as an identity-and-economy problem: give each Friend a useful role, make value consumption visible, and create reasons for repeated participation.`,
    findings: [
      'The Friend should remain the visible operator instead of becoming decorative branding.',
      'Recurring utility creates a stronger RF sink than a one-time cosmetic purchase.',
      'Receipts and persistent progression make each completed action part of the Friend’s history.',
    ],
    opportunities: [
      'Create paid skills that expand what an individual Friend can accomplish.',
      'Let third-party builders publish mission templates priced in RF.',
      'Use earned reputation to unlock advanced work without introducing a speculative token in the MVP.',
    ],
    nextActions: [
      'Validate one complete mission with users before adding more categories.',
      'Measure repeat missions, RF consumed, and successful completion rate.',
      'Design an on-chain provider only after the simulated economy is understandable and useful.',
    ],
  }
}
