import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: 'Explore first' }).click()
})

test('separates the first-visit tour from optional wallet connection', async ({ page }) => {
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  const tour = page.locator('.onboarding')
  await expect(tour.getByRole('heading', { name: 'Your Rare Friend, now at work.' })).toBeVisible()
  await expect(tour.getByText(/wallet is not required/i)).toBeVisible()
  await expect(tour.getByRole('button', { name: /Connect wallet/i })).toHaveCount(0)
  await tour.getByRole('button', { name: 'Explore first' }).click()
  await expect(page.getByText('Connect and sign to load up to three operators and your spendable RF balance.')).toHaveCount(0)
  await page.locator('.top-actions').getByRole('button', { name: /Connect wallet/ }).click()
  const walletModal = page.locator('.wallet-connect-modal')
  await expect(walletModal.getByText('OPTIONAL WALLET CONNECTION')).toBeVisible()
  await expect(walletModal.getByText(/do not need a wallet/i)).toBeVisible()
  await expect(walletModal.getByText(/missions, skills, RF spending, burns, rewards, and progression/i)).toBeVisible()
})

test('turns suggested briefs and structured follow-ups into immediately usable actions', async ({ page }) => {
  await page.getByRole('button', { name: /Research the future of onchain games/ }).click()
  await expect(page.getByLabel('Tell your Friend what you need')).toHaveValue('Research the future of onchain games')
  const launch = page.getByRole('button', { name: /Launch mission/ })
  await expect(launch).toBeEnabled()
  await expect(launch).toHaveClass(/ready/)
  await launch.click()
  await expect(page.locator('.working-scene')).toBeVisible()
  await expect(page.locator('.working-scene')).toHaveAttribute('aria-label', /Signal working at their operator desk/)
  await expect(page.locator('.mission-review')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByLabel('Follow-up instruction')).not.toHaveValue('')
  await expect(page.getByRole('button', { name: /SEND BACK TO SIGNAL/ })).toBeEnabled()
})

test('completes a Research Mission from the unified workspace', async ({ page }, testInfo) => {
  await expect(page.getByRole('heading', { name: 'Your Rare Friend, your new operator.' })).toBeVisible()
  await page.getByLabel('Tell your Friend what you need').fill('Explain the strongest opportunities for Rare Friends builders.')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.getByRole('heading', { name: 'Signal is on it.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Here’s what Signal found.' })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('FOS-48321-0001 / COMPLETE', { exact: true })).toBeVisible()
  if (testInfo.project.name === 'desktop-chromium') await page.screenshot({ path: 'artifacts/friendos-research-result.png', fullPage: true })
  await page.getByRole('button', { name: /Return to workspace/ }).click()
  await expect(page.locator('.history-list article').filter({ hasText: 'FOS-48321-0001' })).toBeVisible()
})

test('switches Friends and navigates the single-page sections', async ({ page }) => {
  await page.getByRole('button', { name: /Switch Friend/ }).click()
  await page.getByRole('button', { name: /Nova/ }).click()
  await expect(page.getByRole('heading', { name: /Nova/ })).toBeVisible()
  await page.getByRole('heading', { name: /Mission history/ }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('heading', { name: /Mission history/ })).toBeVisible()
})

test('opens Skills marketplace and manages an operator wallet', async ({ page }) => {
  await page.getByRole('button', { name: 'Skills' }).click()
  await expect(page.getByRole('heading', { name: /Teach your operator/ })).toBeVisible()
  await expect(page.getByText('20% of every usage fee')).toBeVisible()
  await expect(page.locator('.skill-grid article')).toHaveCount(4)

  await page.getByRole('button', { name: 'Agent profile' }).click()
  await expect(page.getByText('FRIEND WALLET')).toBeVisible()
  await page.getByLabel('Funding amount').fill('25')
  await page.getByRole('button', { name: /Add 25 RF/ }).click()
  await expect(page.locator('.wallet-panel h2')).toContainText('125')
  await page.getByLabel('Per-mission spending limit').fill('4')
  await page.getByRole('button', { name: 'Save spending policy' }).click()
  await page.getByRole('button', { name: /Back to workspace/ }).click()
  await page.getByLabel('Tell your Friend what you need').fill('Research Rare Friends')
  await expect(page.getByRole('button', { name: /Launch mission/ })).toBeEnabled()
})

test('confirms which operator receives a skill and trains a skill NFT', async ({ page }) => {
  await page.getByRole('button', { name: 'Skills' }).click()
  await page.getByRole('button', { name: /INSTALL · 12 RF/ }).click()
  await expect(page.getByRole('heading', { name: /Who will learn Social Signal/ })).toBeVisible()
  await expect(page.locator('.agent-purchase-list label')).toHaveCount(3)
  await page.locator('.agent-purchase-list label').nth(1).click()
  await page.getByRole('button', { name: /Confirm and install/ }).click()
  await page.getByPlaceholder('e.g. Chain Scout').fill('Chain Scout')
  await page.getByRole('button', { name: /Mint free training NFT/ }).click()
  await expect(page.getByText('Approval request')).toBeVisible()
  await page.getByRole('button', { name: 'Approve with caution' }).click()
  await expect(page.getByText(/Judgment XP \+25/)).toBeVisible()
})

test('runs distinct guest missions and opens acquired skill mastery', async ({ page }) => {
  await page.getByRole('button', { name: /Social Content/ }).click()
  await page.getByLabel('Tell your Friend what you need').fill('Announce a new onchain analytics skill')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.getByText(/social campaign designed for clarity/)).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: /Return to workspace/ }).click()
  await page.getByRole('button', { name: 'Agent profile' }).click()
  await page.locator('.profile-pills').getByRole('button', { name: /1 SKILLS/ }).click()
  await expect(page.getByRole('heading', { name: /Abilities that grow through work/ })).toBeVisible()
  await expect(page.locator('.mastery-list small').filter({ hasText: 'MASTERY XP' })).toBeVisible()
})

test('shows dynamic operator capabilities and keeps mission work docked', async ({ page }) => {
  await page.getByRole('button', { name: /What can Signal do/ }).click()
  await expect(page.getByRole('heading', { name: 'What can this operator do?' })).toBeVisible()
  await expect(page.locator('.capability-list').getByText('Deep Research', { exact: true })).toBeVisible()
  await page.locator('.capability-overlay > section > button').click()
  await page.getByLabel('Tell your Friend what you need').fill('Assess wallet activity')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.getByText('MISSION IN PROGRESS')).toBeVisible()
  await expect(page.locator('.workspace')).toBeVisible()
  await expect(page.getByRole('heading', { name: /Here’s what Signal found/ })).toBeVisible({ timeout: 15_000 })
})

test('refines a mission through a structured versioned review', async ({ page }) => {
  await page.getByRole('button', { name: /Social Content/ }).click()
  await page.getByLabel('Tell your Friend what you need').fill('Write a launch announcement for FriendOS')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.getByText('MISSION REVIEW · 0/3 ROUNDS')).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: /^Refine/ }).click()
  await expect(page.getByText('RECOMMENDED SPECIALIST')).toBeVisible()
  await expect(page.locator('.skill-route').getByText('Launch Writer', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'USE NATIVE ABILITY' }).click()
  await page.getByLabel('Follow-up instruction').fill('Rewrite this for NFT collectors and lead with operator ownership')
  await page.getByRole('button', { name: /SEND BACK TO SIGNAL/ }).click()
  await expect(page.getByRole('button', { name: 'V2 · REFINE' })).toBeVisible({ timeout: 5_000 })
  await expect(page.getByText(/Version revised from the instruction/)).toBeVisible()
  await expect(page.getByText('NATIVE CONFIDENCE')).toBeVisible()
  await expect(page.locator('.review-receipt').getByText('+4 MASTERY', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /Return to workspace/ }).click()
  await expect(page.locator('.history-list article').filter({ hasText: '1 REVIEWS' })).toBeVisible()
  await expect(page.locator('.history-list article').filter({ hasText: 'V2' })).toBeVisible()
})

test('installs a routed specialist and credits its review usage', async ({ page }) => {
  await page.getByRole('button', { name: /Social Content/ }).click()
  await page.getByLabel('Tell your Friend what you need').fill('Draft a Rare Friends product announcement')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.getByText('MISSION REVIEW · 0/3 ROUNDS')).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: /^Refine/ }).click()
  await page.locator('.skill-route').getByRole('button', { name: /INSTALL · 15 RF/ }).click()
  await expect(page.locator('.skill-route')).toHaveCount(0)
  await page.getByLabel('Follow-up instruction').fill('Make the announcement shorter and more specific')
  await page.getByRole('button', { name: /SEND BACK TO SIGNAL/ }).click()
  await expect(page.getByText('SPECIALIST CONFIDENCE')).toBeVisible({ timeout: 5_000 })
  await expect(page.getByText('0.4 RF CREATOR')).toBeVisible()
  await expect(page.locator('.review-receipt').getByText('+10 MASTERY', { exact: true })).toBeVisible()
})

test('accepts a result and lets the operator owner edit or delete selected memories', async ({ page }) => {
  await page.getByLabel('Tell your Friend what you need').fill('Map the strongest FriendOS economy opportunity')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.locator('.mission-finalize')).toBeVisible({ timeout: 15_000 })
  await page.locator('.mission-finalize').getByRole('button', { name: 'ACCEPT V1 ↗' }).click()
  await expect(page.locator('.mission-finalize').getByText('Accepted as V1')).toBeVisible()
  await page.getByRole('button', { name: /Return to workspace/ }).click()
  await expect(page.locator('.history-list').getByText('ACCEPTED V1')).toBeVisible()
  await page.getByRole('button', { name: 'Agent profile' }).click()
  const memory = page.locator('.operator-memory')
  await expect(memory.getByText('OPERATOR MEMORY · 2')).toBeVisible()
  const firstMemory = memory.locator('.memory-row').first()
  await firstMemory.getByRole('button', { name: 'EDIT' }).click()
  await firstMemory.getByRole('textbox').fill('Prioritize repeat skill usage with transparent RF receipts.')
  await firstMemory.getByRole('button', { name: 'SAVE' }).click()
  await expect(firstMemory.getByText('Prioritize repeat skill usage with transparent RF receipts.')).toBeVisible()
  await memory.locator('.memory-row').last().getByRole('button', { name: 'DELETE' }).click()
  await expect(memory.getByText('OPERATOR MEMORY · 1')).toBeVisible()
})

test('creates visible linked mission lineage and reopens a completed receipt', async ({ page }) => {
  await page.getByLabel('Tell your Friend what you need').fill('Research the Rare Friends skill economy')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.locator('.mission-finalize')).toBeVisible({ timeout: 15_000 })
  await page.locator('.mission-finalize').getByRole('button', { name: /START LINKED MISSION/ }).click()
  await expect(page.getByLabel('Tell your Friend what you need')).toHaveValue(/Continue from FOS-48321-0001:/)
  await page.getByLabel('Tell your Friend what you need').fill('Continue from FOS-48321-0001: compare two developer revenue models')
  await page.getByRole('button', { name: /Launch mission/ }).click()
  await expect(page.getByText('FOS-48321-0002 / COMPLETE', { exact: true })).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: /Return to workspace/ }).click()
  const history = page.locator('.history-list')
  await expect(history.getByText('CONTINUES FOS-48321-0001')).toBeVisible()
  await expect(history.getByText('CONTINUED AS FOS-48321-0002')).toBeVisible()
  await history.getByRole('button', { name: 'Open result FOS-48321-0001' }).click()
  await expect(page.getByText('FOS-48321-0001 / COMPLETE', { exact: true })).toBeVisible()
})
